config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index', as: :root

  resources :snippets, shallow: true do
    resources :kinds
  end

  get 'kind/:id' => 'snippets#subindex', as: :language
  get '/signup' => 'users#new'
  resources :users, except: [:new]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :snippets, -> {order(created_at: :desc)}, dependent: :nullify
  validates :language, presence: true, uniqueness: true

  def count_for
    return self.snippets.count
  end
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :kind
  belongs_to :user
  validates :work, presence: true
  validates :is_private?, :inclusion => {:in => [true, false]}

  def self.count_by_kind_id(id)
    where(kind_id: id).count
  end

  def self.viewable(user)
    return where(is_private?: false) if user.nil?
    where(user_id: user.id).or(where(is_private?: false))
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :snippets, -> {order(created_at: :desc)}, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence:true,
                       uniqueness: {case_sensitive: false},
                       length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: {maximum: 105},
                    uniqueness: {case_sensitive: false},
                    format: {with: VALID_EMAIL_REGEX}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    session[:user_id].present?
  end

  def require_user
    if !logged_in?
      flash[:danger] = "Please sign in"
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @snippets = Snippet.viewable(current_user).order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def home
    redirect_to snippets_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_snippet, only: [:edit, :update, :destroy, :show]
  before_action :require_user, except: [:index, :show, :subindex]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new snippet_params
    @snippet.user = current_user
    if @snippet.save
      # flash[:success] = 'Snippet Created!'
      redirect_to snippet_path(@snippet)
    else
      flash.now[:danger] = 'Please see the errors below'
      render :new
    end
  end

  def index
    # @snippets = Snippet.all
    @kinds = Kind.all
  end

  def show
  end

  def subindex
    @kind = Kind.find params[:id]
    @snippets = @kind.snippets.viewable(current_user).order(created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def update
    if @snippet.update snippet_params
      flash[:success] = 'Snippet updated!'
      redirect_to snippet_path(@snippet)
    else
      # flash.now[:danger] = 'See errors below'
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    flash[:danger] = 'Snippet was deleted!'
    redirect_to snippets_path
  end

  private

  def snippet_params
    params.require(:snippet).permit(:title, :work, :kind_id, :is_private?)
  end

  def find_snippet
    @snippet = Snippet.find(params[:id])
  end

  def require_same_user
    if current_user != @snippet.user
      flash[:danger] = "You can only edit or delete your own snippets"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the snippet #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "You account was updated successfully!"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def show
    @user_snippets = @user.snippets.viewable(current_user).paginate(page: params[:page], per_page: 5)
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
        Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      :autolink => true,
      :no_intra_emphasis => true,
      :disable_indented_code_blocks => true,
      :fenced_code_blocks => true,
      :lax_html_blocks => true,
      :strikethrough => true,
      :superscript => true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center">
  <% if logged_in? %>
    <h3>Hello, <%= current_user.username %></h3>
  <% end %>
  <h1>Welcome to Code Snippets</h1>
  <%# link_to "Sign up as admin", signup_path, class:"btn btn-danger btn-sm" %>
  <div class="center">
    <%= will_paginate @snippets %>
  </div>
  <% @snippets.each do |s| %>
    <%# if !s.is_private? %>
      <div class="well col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="post-title">
            <%= link_to s.title, snippet_path(s) %>
          </div>
          <% if s.user %>
          <hr>
          <!-- <ul class="listing"> -->
            <div class="row center">
              <div class="col-md-6 col-md-offset-3">
                <h5>Created by: <%= link_to s.user.username, user_path(s.user) %> | Language: <%= link_to s.kind.language, language_path(s.kind.id) %></h5>
              </div>
            </div>
          <!-- </ul> -->
        <% end %>
          <div class="post-body">
            <%= markdown("```" + s.kind.language + "\n" + s.work + "\n```") %>
          </div>
          <% if logged_in? && current_user == s.user %>
            <div class="post-actions">
              <%= link_to 'Edit', edit_snippet_path(s), class: "btn btn-xs btn-primary" %>
              <%= link_to 'Delete', snippet_path(s),
                                method: :delete,
                                data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    <%# end %>
  <% end %>
  <div class="center">
    <%= will_paginate @snippets %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeSnippets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'highlight', 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h4 class="center">
      <%= link_to "Home", root_path %> |
      <%= link_to "View all snippets", snippets_path %> |
      <% if logged_in? %>
        <%= link_to "Create new snippet", new_snippet_path %> |
        <%= link_to "Edit your profile", edit_user_path(current_user) %> |
        <%= link_to "View your work", user_path(current_user) %> |
        <%= link_to 'Log out', logout_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign up', signup_path %> |
        <%= link_to 'Log in', login_path %>
      <% end %>
    </h4>
    <%= render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this post from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<%= render 'shared/errors', obj: @snippet %>
<h1 class="center">Edit Code Snippet</h1>
<hr>

<div class="row">
  <div class="well col-xs-12">
    <%= form_for(@snippet, html: { class: "form-horizontal", role: "form"}) do |f| %>
    <div class = "form-group">
      <div class = "control-label col-sm-2">
        <%= f.label :kind %>
      </div>
      <div class="col-sm-2">
        <div class="dropdown">
          <%= f.collection_select :kind_id, Kind.all, :id, :language, :prompt => true %>
        </div>
      </div>
    </div>
    <div class = "form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of snippet", autofocus: true %>
      </div>
    </div>
    <div class = "form-group">
      <div class="control-label col-sm-2">
        <%= f.label :work %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :work, rows: 10, class: "form-control", placeholder: "Body of snippet" %>
      </div>
    </div>
    <div class = "form-group">
      <div class="control-label col-sm-3">
        <label class="checkbox-inline">
          <input type="hidden" id="blankCheckbox" value=false >
          <input type="checkbox" id="blankCheckbox" value="private" ><span id="private">Private?</span>
        </label>
      </div>
    </div>
    <div class = "form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :Save, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/snippets/index.html.erb
<h1 class="center">Code Snippets</h1>
<div align="center">
  <% @kinds.each do |kind| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <h4><%= link_to "#{kind.language}", language_path(kind.id) %></h4>
          </li>
          <li><small><%= pluralize(kind.count_for, "snippet") %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/snippets/new.html.erb
<%= render 'shared/errors', obj: @snippet %>
<h1 class="center">Create a Code Snippet</h1>
<hr>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@snippet, html: { class: "form-horizontal", role: "form"}) do |f| %>
    <div class = "form-group">
      <div class = "control-label col-sm-2">
        <%= f.label :kind %>
      </div>
      <div class="col-sm-2">
        <div class="dropdown">
          <%= f.collection_select :kind_id, Kind.all, :id, :language, :prompt => true %>
        </div>
      </div>
    </div>
    <div class = "form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of snippet", autofocus: true %>
      </div>
    </div>
    <div class = "form-group">
      <div class="control-label col-sm-2">
        <%= f.label :work %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :work, rows: 10, class: "form-control", placeholder: "Body of snippet" %>
      </div>
    </div>
    <div class = "form-group">
      <div class="control-label col-sm-3">
        <label class="checkbox-inline">
          <%= f.check_box :is_private?, {}, "1", "0" %>
          <input name="snippet[is_private?]" type="hidden" value="0" >
          <input id="snippet_is_private?" name="snippet[is_private?]" type="checkbox" value="1" ><span id="private">Private?</span>
        </label>
      </div>
    </div>
    <div class = "form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :Save, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/snippets/show.html.erb
<div class="well col-xs-8 col-xs-offset-2">
  <% if !@snippet.is_private? || (logged_in? && current_user == @snippet.user) %>
    <h2 align="center">Title: <%= @snippet.title %></h2>
    <% if @snippet.user %>
    <!-- <ul class="listing"> -->
      <div class="row center">
        <div class="col-md-6 col-md-offset-3">
          <h5>Created by: <%= link_to @snippet.user.username, user_path(@snippet.user) %> <%= @snippet.is_private?  ?  "| Private" : "| Public" %></h5>
        </div>
      </div>
    <!-- </ul> -->
  <% end %>
    <h3 align="center">Language: <span class="language"><%= link_to @snippet.kind.language, language_path(@snippet.kind.id) %></span></h3>
    <div class="post-actions">
      <!-- <h4 class="center description"><strong>Work:</strong></h4> -->
      <hr>
      <%= markdown("```" + @snippet.kind.language + "\n" + @snippet.work + "\n```") %>
      <%# block_code(@snippet.work, @sinppet.kind.language) %>
      <div class="post-actions">
        <% if logged_in? && current_user == @snippet.user %>
          <%= link_to 'Edit', edit_snippet_path(@snippet), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Delete', snippet_path(@snippet),
                            method: :delete,
                            data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to 'View all', snippets_path, class: "btn btn-xs btn-success" %>
      </div>
    </div>
  <% else %>
    <h2 class="center">This snippet is private</h2>
  <% end %>
</div>

app/views/snippets/subindex.html.erb
<h3 align="center">Writen by:<span class="language"> <%= @kind.language %></span></h3>
<div class="center">
  <%= will_paginate @snippets %>
</div>
<% @snippets.each do |s| %>
  <%# if !s.is_private? %>
    <div class="well col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="post-title">
          <%= link_to s.title, snippet_path(s) %>
        </div>
        <% if s.user %>
        <!-- <ul class="listing"> -->
          <div class="row center">
            <div class="col-md-4 col-md-offset-4">
              <h5>Created by: <%= link_to s.user.username, user_path(s.user) %></h5>
            </div>
          </div>
        <!-- </ul> -->
      <% end %>
        <div class="post-body">
          <%= markdown("```" + s.kind.language + "\n" + s.work + "\n```") %>
        </div>
        <% if logged_in? && current_user == s.user %>
          <div class="post-actions">
            <%= link_to 'Edit', edit_snippet_path(s), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete', snippet_path(s),
                              method: :delete,
                              data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  <%# end %>
<% end %>
<div class="center">
  <%= will_paginate @snippets %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class = "form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class = "form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class = "form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class = "form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1 align="center">Signup for Posting</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s snippet page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%# gravatar_for @user, size: 150%>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s snippets</h4>
<div class="center">
  <%= will_paginate @user_snippets %>
</div>
<hr>
<br>
<% @user_snippets.each do |s| %>
    <div class="well col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="post-title">
          <%= link_to s.title, snippet_path(s) %>
        </div>
        <div>
          <h5 align="center">Writen by:<span class="language"> <%= s.kind.language %></span></h5>
        </div>
        <div class="post-body">
          <%= markdown("```" + s.kind.language + "\n" + s.work + "\n```") %>
        </div>
        <% if (logged_in? && current_user == s.user) %>
          <div class="post-actions">
            <%= link_to 'Edit', edit_snippet_path(s), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete', snippet_path(s),
                              method: :delete,
                              data: {confirm: 'Are you sure?'}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
<% end %>

<div class="center">
  <%= will_paginate @user_snippets %>
</div>